"""Numerical norm audit for left-invariant one-forms on S3.

Scope:
    Safe P1-NORM numerical diagnostic only. Despite the historical filename,
    this module does not implement a kNN connection Laplacian on one-forms.

    A graph connection Laplacian would require a separately validated discrete
    connection, parallel transport rule, and convergence proof. The diagnostic
    here only checks the Haar/Muller pointwise norm and Gram matrix of the
    left-invariant coframe embedded in R4.
"""

from __future__ import annotations

from typing import Any

import numpy as np


DIRECT_HAAR_TARGET_NORM = 1.0
TEMPORARY_ENGINEERING_TARGET_NORM = DIRECT_HAAR_TARGET_NORM


def sample_s3_muller(n_points: int, seed: int = 20260607) -> np.ndarray:
    """Sample points uniformly on unit S3 using Muller normalization."""
    if n_points <= 0:
        raise ValueError(f"n_points must be positive, got {n_points!r}")

    rng = np.random.default_rng(seed)
    samples = rng.normal(size=(n_points, 4))
    norms = np.linalg.norm(samples, axis=1)
    return samples / norms[:, None]


def left_invariant_frame_vectors(points: np.ndarray) -> np.ndarray:
    """Return three left-invariant tangent vectors at each S3 point.

    Points are treated as unit quaternions ``q = a + b i + c j + d k``. The
    frame is generated by left multiplication by ``i,j,k``.
    """
    points = np.asarray(points, dtype=float)
    if points.ndim != 2 or points.shape[1] != 4:
        raise ValueError("points must have shape (n_points, 4)")

    a = points[:, 0]
    b = points[:, 1]
    c = points[:, 2]
    d = points[:, 3]

    e1 = np.column_stack((-b, a, -d, c))
    e2 = np.column_stack((-c, d, a, -b))
    e3 = np.column_stack((-d, -c, b, a))
    return np.stack((e1, e2, e3), axis=1)


def compute_e_coframe_norm_numerical(
    n_points: int = 5000,
    k_neighbors: int = 20,
    seed: int = 20260607,
) -> dict[str, Any]:
    """Numerically audit the left-invariant coframe norm on S3.

    ``k_neighbors`` is accepted for API continuity with the rejected graph
    Laplacian design, but no kNN graph is built in this safe diagnostic.
    """
    if k_neighbors <= 0:
        raise ValueError(f"k_neighbors must be positive, got {k_neighbors!r}")

    points = sample_s3_muller(n_points=n_points, seed=seed)
    frame = left_invariant_frame_vectors(points)
    pointwise_gram = np.einsum("pia,pja->pij", frame, frame)
    gram_matrix = np.mean(pointwise_gram, axis=0)
    component_norms = np.sqrt(np.diagonal(pointwise_gram, axis1=1, axis2=2))
    mean_component_norms = np.mean(component_norms, axis=0)
    mean_raw_norm = float(np.mean(mean_component_norms))
    gram_eigenvalues = np.linalg.eigvalsh(gram_matrix)

    return {
        "method": "Haar/Muller left-invariant coframe norm audit",
        "graph_laplacian_status": "not_implemented_by_design",
        "reason_graph_laplacian_skipped": (
            "connection Laplacian on one-forms needs a validated discrete "
            "connection and parallel transport; this diagnostic only checks norm"
        ),
        "n_points": int(n_points),
        "k_neighbors_requested": int(k_neighbors),
        "seed": int(seed),
        "raw_component_norms_mean": mean_component_norms.tolist(),
        "raw_component_norm_mean": mean_raw_norm,
        "direct_haar_target_norm": DIRECT_HAAR_TARGET_NORM,
        "temporary_engineering_target_norm": TEMPORARY_ENGINEERING_TARGET_NORM,
        "scale_to_direct_haar_norm": (
            DIRECT_HAAR_TARGET_NORM / mean_raw_norm
        ),
        "scale_to_temporary_engineering_norm": (
            TEMPORARY_ENGINEERING_TARGET_NORM / mean_raw_norm
        ),
        "gram_matrix": gram_matrix,
        "diagnostic_spectrum": gram_eigenvalues,
        "operator_hermitian": bool(np.allclose(gram_matrix, gram_matrix.T.conjugate())),
        "claim_scope": (
            "numerical norm diagnostic only; not Ben Achour E/E' basis mapping "
            "and not a one-form Laplacian spectrum"
        ),
    }
